### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by goulartgabriel** [goulartgabriel/ir_calculator#1]
### Script is currently returning current portfolio from a PDF file

- [ ] check if there are any orders contained in PDF file that need to pay IR (>20k)
- [x] compute portfolio from multiple PDF files
- [x] return spreadsheet with current portfolio
- [ ] script needs to consider all of the possibilities in `Obs` column (listed on footnotes)
- [ ] build static Github page showing dataframe
